Update optional syntax
dapperlabs-platform/terraform-gcp-spanner pull request #14
Opened 2023-02-26 12:17 UTC by mtmendonca

Update optional syntax

2023-02-26 15:01 UTC, noyceb requested changes, later dismissed

2023-02-26 15:01 UTC, noyceb commented on main.tf
> +  display_name     = var.name
We can't remove this due to backward compatibility for Spanner instances like in RnD projects.  Can I suggest we default `display_name` to `name` if it's not set?

2023-02-26 23:32 UTC, noyceb commented on main.tf
> +  display_name     = var.name
`display_name` is fine to change, but legacy spanner instances have different `name` values.  Resolving this convo.

2023-02-26 23:38 UTC, noyceb commented
Removed my block - I'm not a super fan of removing `display_name` over making it optional in the same way as other variables, especially since it might be getting set to the name anyway, so letting someone else weigh in here.

2023-02-27 12:50 UTC, haroldsphinx approved these changes

2023-02-27 12:50 UTC, merged